### ISSUE TITLE
4.0.1 breaks Python 3.6 support

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [mdavidsaver/p4p#85] opened 2022-05-23 09:16 UTC
Version 4.0.1 breaks support for python 3.6, due to using the `asyncio.get_running_loop()` function which is new in Python 3.7. 

An example of the change [can be seen here](https://github.com/mdavidsaver/p4p/commit/d687a3201bab4f81d08441f07817c59dee6e019c#diff-1abe04bb19e5326df73c33aa5cd1d4c30ebb224a8a642b7db0ef14b7e4fd964cR145). This breaks pythonSoftIOC's CI, which [can be seen here](https://github.com/dls-controls/pythonSoftIOC/runs/6551492513?check_suite_focus=true#step:5:602).

Version 4.0.0 was still compatible with Python 3.6. We did not expect support to be dropped in a patch version update.

Thank you for any information.

**Comment by mdavidsaver** [comment] 2022-05-23 13:44
I think this is a duplicate of #84

**Closed by mdavidsaver** 2022-05-23 13:44 UTC
Labels: duplicate
